local_repository(
    name = "io_bazel_rules_dotnet",
    path = "../..",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
)

dotnet_register_toolchains()

dotnet_repositories_nugets()

# load NUGET deps
load("//:gen/nuget.bzl", "project_dotnet_repositories_nuget")

project_dotnet_repositories_nuget()
