filegroup(
    name = "bzl_srcs",
    srcs = glob(["**/*.bzl"]),
    visibility = ["//docs:__pkg__"],
)

exports_files([
    "nunit/shim.cs",
    "nunit/shim.fs",
    "runtimeconfig.json.tpl",
    "deps.json.tpl",
    "launcher.sh.tpl",
    "launcher.bat.tpl",
])
