workspace(name = "ef")

local_repository(
    name = "io_bazel_rules_dotnet",
    path = "../../..",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "core_register_sdk",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
)

dotnet_register_toolchains()

dotnet_repositories_nugets()

core_register_sdk()

# load NUGET deps
load("//:nuget.bzl", "project_dotnet_repositories_nuget")

project_dotnet_repositories_nuget()
